### PR TITLE
Blog post

### PR DESCRIPTION
**Pull request by alessandrobenedetti**
From staging to prod

### CODE REVIEW

**Comment by alessandrobenedetti** [comment]
@janhoy apparently there are conflicts, not sure why this could happen?

Also I noticed that It didn't squash the commits from the blog pull request, is it something we don't do for the site?
Normally it does it automatically for the solr code

**Comment by janhoy** [comment]
Resolved!

**Comment by alessandrobenedetti** [comment]
hi @janhoy  when are we supposed to see the changes online?
I took a look this morning and it's not there yet?

**Comment by janhoy** [comment]
> hi @janhoy when are we supposed to see the changes online? I took a look this morning and it's not there yet?

https://solr.apache.org/blog.html

**Pull request merged**
