### PR TITLE
SOLR-15557 Old refguide page redirects

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/SOLR-15557

* Added a new `guide/htaccess.template` to handle all the guide specific redirects
* See https://github.com/apache/solr/pull/596 for a script to generate the redirects for Antora

### CODE REVIEW

**Comment by uschindler** [comment]
For sich long redirect maps it might be better to put them into a separate file. Like with email values a hashmap using a dbm file might be better. There's also RedirectMap: https://httpd.apache.org/docs/2.4/rewrite/rewritemap.html

The file could be generated by the script. Too. But converted to dbm afterwards. We might do a simple test on staging if the ASF Apache Server supports them.

**Comment by uschindler** [comment]
I figured out: RewriteMap is not allowed in htaccess files.
I used them quite often on huge servers before I changed to maps in nginx.

**Comment by janhoy** [comment]
I wonder if we could put all these directives in a separate `guide/.htaccess` file instead of in the top-level one? Not sure if that will work since `guide/` really does not exist but is rewritten to `__root`.

**Comment by janhoy** [comment]
PS: I have updated the redirect rules in https://github.com/apache/solr/pull/596 but not here. Will copy everything over to this PR for commit when we feel it is ready.

**Comment by uschindler** [comment]
We can still have a guide directory and htaccess should work there. We may only need to copy over the guide specific rewrites, too.
The guide directory exists, the patterns only match on there versioned dubdir. So yes it's a good idea because it would prevent web server from uselessly processing all of them on other folders.

**Comment by janhoy** [comment]
@uschindler This PR now adds the new `guide/.htaccess` file. Tested with a local httpd, like this:

```
./build.sh
docker run --rm --name httpd -p 8000:80 -v $(pwd)/output:/usr/local/apache2/htdocs/ -v $(pwd)/my-httpd.conf:/usr/local/apache2/conf/httpd.conf httpd
```

You can then test that these redirects work (foo is a test page rename):
```
http://localhost:8000/guide/1_2          -> http://localhost:8000/guide/1_2/
http://localhost:8000/guide/foo.html     -> http://localhost:8000/guide/solr-glossary.html
http://localhost:8000/guide/abc.html     -> http://localhost:8000/guide/8_11/abc.html
```

**Review by uschindler — APPROVED** [review]
I was also not able to fully test this. Easiest would be to merge this and try out if everything works on production page.

I am not fully sure if the rewrites for the static files works,  it looks like you tried out because you reverted some parts. I think it works because multiple htaccess files are applied on top of each other. So if you are inside the guide directory, it would apply rules from there, but the rules from the parent file, too.

**Comment by janhoy** [comment]
Tried this by merging (and sorry for not squash-merging, became a bit noisy).

While the rules in `guide/.htaccess` worked in isolation, unfortunately I could not
* get it to inherit rules from parent with `RewriteOptions Inherit` - it should then have applied parent rules after local rules
* replicate the last two rules from main htaccess into the local guide/htaccess, as it is illegal to redirect to parent folder, and the `__root/docs.solr.apache.org/` folder is only available on the root level.

I think, to make this work, we need to either
* Find a way to make inheritance work. Could be that inheritance is disallowed by main httpd config file?
* or have infra make another symlink to `__root...` inside the guide folder, but that is dirty..
* add all the redirects to the main .htaccess file and take the performance hit
* ask INFRA to add our rewrites as a map in the main config. This is more performant, but a hassle to maintain

**Comment by janhoy** [comment]
Looks like mod_rewrite inheritance is useless, as it simply copies applies the root rewrite rules, but in the **context of the sub folder**, i.e. `^(docs|guide)/\d+.*$` will not match, see https://stackoverflow.com/questions/60152286/rewriterule-in-folder-breaks-parent-htaccess

**Comment by uschindler** [comment]
OK, let's keep with a single htaccess file on root level. We will see if INFRA complains about slowness. Maintenance is another fact (but how long do we need to geep the redircets?). As all folders are versioned we only need the top-level redirects for a while until all search engines have updated their links.

RewriteMap would be cool, but when looking at the whole folder layout: Couldn't it be simplified with a few regular expression redirects? To me it looks like something like this:

```
RedirectMatch ^/guide/(file1|file2|file3)\.html /guide/subdir1/$1.html
RedirectMatch ^/guide/(file4|file5|file6)\.html /guide/subdir2/$1.html
```
 Of course if there are also file renames that won't work.

**Comment by janhoy** [comment]
I also converted the 8_11 redirects into one line:
> RedirectMatch ^/guide/(adding-custom-plugins-in-solrcloud-mode|blob-store-api|cdcr-api|cdcr-architecture|cdcr-config|cdcr-operations|colocating-collections|cross-data-center-replication-cdcr|dataimport-screen|metrics-history|migrate-to-policy-rule|rule-based-replica-placement|solrcloud-autoscaling-api|solrcloud-autoscaling-auto-add-replicas|solrcloud-autoscaling-fault-tolerance|solrcloud-autoscaling-listeners|solrcloud-autoscaling-overview|solrcloud-autoscaling-policy-preferences|solrcloud-autoscaling-trigger-actions|solrcloud-autoscaling-triggers|solrcloud-autoscaling|suggestions-screen|uploading-structured-data-store-data-with-the-data-import-handler|velocity-response-writer|velocity-search-ui)\.html /guide/8_11/$1.html

**Comment by uschindler** [comment]
Thanks, this should be fine, as the regexes are compiled and applied (as we all know from Lucene) as a state machine. I have not checked the synatx, we may need to add the 301 / perm and so on.

**Comment by janhoy** [comment]
See https://github.com/apache/solr/pull/596/commits/171922e03e583088e3bf471be4a698dddf7bb19e

**Pull request merged**
