### PR TITLE
Create 2024-07-15-apache-solr-performance-jmeter.md

### PR DESCRIPTION
**Pull request by lizbiella**
I added a new blog post about the Apache Solr Performance test.

### CODE REVIEW

**Review by janhoy — APPROVED** [review]
Looks good.
Only general comment I have is that we shuold find a way to make it obvious that the links are to an external site. Either in plain text, e.g. (external link) or by using some icon like 🔗 or ⤴. Or perhaps we could introduce a custom metadata `external_url` in header that generates a uniform box at the bottom of the post with the external link?

This can be done in a later issue though, so feel free to merge this.

**Comment by lizbiella** [comment]
Thanks @janhoy ! I will add "(external link)" for the next blog post. Feel free to comment in the next pull request if you think it is better to change it.

**Comment by lizbiella** [comment]
@janhoy I can't see the blog post on the online page. Did something go wrong? Do I need to do something else?

**Comment by janhoy** [comment]
Perhaps you forgot to merge to production branch?

**Comment by janhoy** [comment]
I merged to production now.

**Pull request merged**
