### PR TITLE
Options for Solr Operator logos

### PR DESCRIPTION
**Pull request by mhmonac**
Hello everyone, new to the community but I was asked to help out with some logos for the new Solr Operator sub-project. This is related to PR #11.

I have a few options available, but we can add more variants or make changes if needed 🙂 

Please take a look and make suggestions if you have any! It looks like the text is a bit mangled at this size, but I can always export it at a higher resolution.

(I'm very excited as this is my first open source PR! Please let me know if theres something else I'm supposed to do.)

Solr_Operator_Logo_Name_Colorful
Solr_Operator_Logo_Name
Solr_Operator_Logo_Icon

### CODE REVIEW

**Comment by janhoy** [comment]
I like the simplicity.

However, can you try with solid "Solr-red" color instead of the gradient? Simpler is better.
Also, I think it will be better with lowercase 'o' in 'operator'.

Do we need both the hexagon and the rudder to recognize the k8s link? What about a circular 'o' with the k8s rudder inside? Or alternatively just the hexagon without the full rudder inside?
image

**Comment by mhmonac** [comment]
Thanks for the suggestions! Here are some adjustments:

Solr_Operator_Logo_Hexagon

Solr_Operator_Logo_Wheel

Solr_Operator_Logo_Full

Solr_Operator_Logo_Icon_Solid
^ I'm not a huge fan of this...

Solr_Operator_Logo_Icon_Gradient

**Comment by janhoy** [comment]
I like several of these.

@HoustonPutman May perhaps we have come far enough to go to voting? I propose that you label each candidate as A, B, C... and initiate a vote in the community, wherever that may be? users@solr mailing list? And of course we also need a version that works on dark backgrounds, and we need SVG originals, but that can come after the vote.

**Comment by HoustonPutman** [comment]
Hey @mhmonac, would you mind trying the gradient Icon with a dark-gray wheel? I think that would look quite nice.

**Comment by mhmonac** [comment]
Here are other variants: 

Solr_Operator_Logo_Full_Gradient

Solr_Operator_Logo_Icon_Gradient_Gray

Let me know if you want any other!

**Comment by HoustonPutman** [comment]
Thanks!

**Comment by janhoy** [comment]
So given these all infringe the Kubernetes trademarks, I guess we have to re-boot this process? And close this PR

**Pull request closed without merging**
